import Footer from "@/components/footer";
import Header from "@/components/header";
import Logo from "@/components/logo";
import Switcher from "@/components/switcher";
import classNames from "classnames";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="space-y-32">
        {/* Hero */}
        <section className="bg-[url('/images/hero.jpg')] bg-cover bg-no-repeat bg-center h-[80vh]">
          <div
            className={classNames(
              "bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-black/30 to-black/70",
              "backdrop-blur-sm",
              "h-full w-full",
              "flex items-center justify-center"
            )}
          >
            <div className="w-full h-full max-w-7xl p-8">
              <h1 className="sr-only">Esprit Primeur</h1>
              <Switcher
                delay={5000}
                childrens={[
                  <Logo
                    artifact="pear"
                    className="h-[80%] w-auto max-w-full text-white"
                  />,
                  <Logo
                    artifact="carrot"
                    className="h-[80%] w-auto max-w-full text-white"
                  />,
                  <Logo
                    artifact="strawberry"
                    className="h-[80%] w-auto max-w-full text-white"
                  />,
                ]}
                childrenClassName="w-full h-full flex flex-col items-center justify-center"
              />
            </div>
          </div>
        </section>
        {/* About */}
        <section className="max-w-7xl mx-auto">
          <div className="flex flex-row">
            <div className="flex-1 bg-red-50">
              <Image
                src="/images/about.jpg"
                width={700}
                height={700}
                alt="Test"
                className="object-cover w-full h-full object-center"
              />
            </div>
            <div className="flex-1 space-y-4 px-8 py-4">
              <h2 className="font-medium tracking-tight text-3xl">
                Qui sommes-nous ?
              </h2>

              <p>
                Théophile et Natalia BENOIST gèrent ensemble et depuis
                maintenant plus de 3 ans le commerce fruits et légumes du centre
                bourg de Biscarrosse anciennement nommé "Chez Popaul"
                aujourd'hui appelé "ESPRIT PRIMEUR".
              </p>
              <p>
                C'est leur 3ème magasin, après avoir passé plusieurs années en
                tant que primeur sur la commune de Cestas et Pessac, ils
                décident de se concentrer sur ce magasin et d'y développer leur
                savoir-faire, leurs connaissances ainsi que tous les projets
                qu'ils ont en tête.
              </p>
              <p>
                Amoureux de leur métier, ils ont décroché en février 2023 le
                titre de "Talent fruits et légumes" d'abord sur la région grand
                Sud-Ouest puis au niveau national.
              </p>
              <blockquote className="border-l-4 border-gray-300 px-4 text-gray-700">
                <span className="font-semibold">{`Théophile : `}</span>La plus
                belle des récompenses et la reconnaissance de notre travail par
                nos pairs, une grande fierté pour nous, notre équipe et nos
                clients.
              </blockquote>
              <p>
                Commerçants avant tout, ils sont dans la démarche active d'être
                aussi reconnus comme artisans. En effet, ils ne se contentent
                pas seulement de revendre des fruits et légumes, ils essaient
                aussi dans une démarche anti-gaspillage de valoriser les
                produits destinés à être jetés par la transformation de certains
                produits en confiture artisanales, en confiseries, en jus de
                fruits, en conserves.
              </p>
              <blockquote className="border-l-4 border-gray-300 px-4 text-gray-700">
                <span className="font-semibold">{`Natalia : `}</span>Dans notre
                domaine d'activité il y a énormément de gaspillage alimentaire,
                Il fallait trouver une solution pour y remédier, c'est pour cela
                que la transformation de certains produits est une idée qui
                s'est naturellement mise en place.
              </blockquote>
              <p>
                Théophile et Natalia ont encore une multitude d'idées à mettre
                en place, afin de développer les prestations proposées à leurs
                clients mais toujours autour du fruit et du légumes, et toujours
                dans le but de les satisfaire !
              </p>
              <blockquote className="border-l-4 border-gray-300 px-4 text-gray-700">
                <span className="font-semibold">{`Théophile : `}</span>Ces
                projets ne seraient pas envisageables si nous n'avions pas cette
                équipe !"
              </blockquote>
              <p>
                L'équipe ESPRIT PRIMEUR se compose de Josiane, Alexandre et
                Alexia. Équipe compétente et soudée elle saura vous accueillir
                tout au long de la journée avec le sourire et pour vous
                conseiller lors de vos achats.
              </p>
              <p>L'équipe vous attend nombreux !</p>
            </div>
          </div>
        </section>
        {/* Promotion */}
        <section className="max-w-7xl mx-auto">
          <iframe
            width="343"
            height="610"
            src="https://www.youtube.com/embed/mcF12tmkEmE"
            title="découverte du magasin esprit primeur - BISCARROSSE"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          ></iframe>
        </section>
        {/* Shop */}
        <section className="max-w-7xl mx-auto">
          <div className="bg-[url('/images/shop.jpg')] bg-cover bg-no-repeat bg-center">
            <div className="bg-black/20">
              <div className="mx-auto py-32">
                <h2 className="font-medium tracking-tight text-3xl">
                  Le magasin
                </h2>
              </div>
            </div>
          </div>
          <div className="flex">
            <div className="flex-1">Infos</div>
            <div className="flex-1 bg-red-50">MAP</div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
