import Footer from "@/components/footer";
import Header from "@/components/header";
import ProductPage from "@/components/product-page";
import ProductPriceBullet from "@/components/product-price-bullet";
import Head from "next/head";

export async function getStaticProps() {
  return {
    props: {},
  };
}

export default function Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ProductPage
        value={{
          name: "Les buffets",
          assets: "/images/apicius/products/buffets",
          assetsConfig: {
            detailsExtension: "gif",
          },
        }}
        renderDetails={
          <>
            <p>
              {`Les buffets que je propose sont élaborés en fonction de vos
              envies, de vos goûts et surtout de votre budget.`}
            </p>
            <p>
              {`Je réalise des buffets principalement "veggie", je peux vous
              proposer des verrines/mignardises comprenant un peu de fromage ou
              de charcuterie, l'utilisation d'autres produits l'été.`}
            </p>
          </>
        }
        renderPrices={
          <>
            <p>
              {`Les tarifs sont à définir en fonction de vos envies, demande sur
              devis`}
            </p>
            <div className="flex flex-col gap-y-2 pt-4">
              <span className="font-bold">
                {`Pour vos lendemains de festivités, je vous propose une formule
                brunch pour 20€ par personnes comprenant :`}
              </span>
              <ProductPriceBullet>
                Viennoiseries (
                <span className="underline font-semibold">minimum 2</span> par
                personne)
              </ProductPriceBullet>
              <ProductPriceBullet>
                {`Gauffres sucrées et sélection de confitures faites maison (2
                parfums)`}
              </ProductPriceBullet>
              <ProductPriceBullet>
                {`1 jus de fruits frais (orange et/ou smoothie avec des fruits de
                saison)`}
              </ProductPriceBullet>
              <ProductPriceBullet>
                {`1 salade de fruits (fruits de saison)`}
              </ProductPriceBullet>
              <ProductPriceBullet>
                {`2 assortiments de crudités en libre-service`}
              </ProductPriceBullet>
              <ProductPriceBullet>
                {`2 sauces tartinables au choix : Houmous, caviar d'aubergine,
                guacamole, tapenade verte ou noire ou Tomatade (faites maison) +
                pain`}
              </ProductPriceBullet>
              <ProductPriceBullet>
                {`Gaufres salées (choix du légumes, recommandé courgette)`}
              </ProductPriceBullet>
              <ProductPriceBullet>
                {`Assortiments de fruits frais`}
              </ProductPriceBullet>
            </div>
          </>
        }
      />
      <Footer mode="apicius" />
    </>
  );
}
